// ===============================================================
// PRODUCTION
// ===============================================================

// -----------------------
// COURSES
// -----------------------

### Get all courses
GET https://university-management-system-b55v.onrender.com/courses

### Get course by id
GET https://university-management-system-b55v.onrender.com/courses/6921b75c1207593db4d5dcc3

### Create course
POST https://university-management-system-b55v.onrender.com/courses HTTP/1.1
content-type: application/json

{
    
    "courseCode": "MATH101",
    "courseName": "Calculus I",
    "department": "Mathematics",
    "instructor": "Jane Doe",
    "credits": 4,
    "startDate": "2023-09-10",
    "maxStudents": 50,
    "description": "Introduction to limits and derivatives."
}

### Update course
PUT https://university-management-system-b55v.onrender.com/courses/6921c1422afbc9c2a4e20966 HTTP/1.1
content-type: application/json

{
    "courseCode": "MATH101",
    "courseName": "Integration",
    "department": "Mathematics",
    "instructor": "Nephi Asha",
    "credits": 4,
    "startDate": "2023-09-10",
    "maxStudents": 25,
    "description": "Integration class"
}

### Delete course
DELETE https://university-management-system-b55v.onrender.com/courses/6921c1422afbc9c2a4e20966


// -----------------------
// STUDENTS
// -----------------------

### Get all students
GET https://university-management-system-b55v.onrender.com/students

### Get student by id
GET https://university-management-system-b55v.onrender.com/students/6921b8c8d7a85fa73c46684c

### Create student
POST https://university-management-system-b55v.onrender.com/students HTTP/1.1
content-type: application/json

{
    "firstName": "Bebe",
    "lastName": "Oto",
    "email": "ot0@gmail.com",
    "major": "Business Managemenet",
    "enrollmentDate": "2024-01-10",
    "birthday": "2006-11-29"
}

### Update student
PUT https://university-management-system-b55v.onrender.com/students/6921c20c2afbc9c2a4e20967 HTTP/1.1
content-type: application/json

{
    "firstName": "Bebe",
    "lastName": "Otobong",
    "email": "beb@afro.net",
    "major": "Hospitality",
    "enrollmentDate": "2024-01-10",
    "birthday": "2006-11-29"
}

### Delete student
DELETE https://university-management-system-b55v.onrender.com/students/6921b8c8d7a85fa73c46684c